### ISSUE TITLE
Doesn't work with plugin.video.netflix

### ISSUE THREAD

**Issue by lameventanas** [enen92/service.sleeptimer#11]
The sleep timer doesn't work with the Netflix plugin.

If I activate the sleep "When video ends", and play a Netflix video, it won't get triggered when the video playback ends.

**Comment by enen92** [comment]
The service tracks idle time in Kodi which means that if you are watching Netflix after an episode ends another one will start and the idle time will most likely be set to zero again. The addon was made for live content mostly. I've to check with my netflix account.
What is your setup in Netflix? Do you autoplay next episodes?

**Comment by lameventanas** [comment]
Sorry, I just realized I'm not using service.sleeptimer, but script.sleep.

Please disregard.
